pub mod hardware;
// use hardware::{ mock_hardware, ni_usb6001 };
mod error;
pub use self::error::{Error, Result};
pub mod datapoint;
pub mod channel;
pub mod device;
pub mod daq;
pub mod storage_hdf;
pub mod storage_csv;
pub mod configuration;