//! Raw driver bindings.
//!
//! Everything here is generated by bindgen and everything here is `unsafe`.
//! bindgen translates the header's syntax, not its meaning: it does not know
//! that a handle must come from an open call, that a returned 0 means failure,
//! or that a pointer argument needs storage you own. That knowledge lives in
//! the safe wrappers one level up, which is the only place these are called.

pub mod hrdl;
