//! Pico Technology data loggers.
//!
//! The drivers are C libraries loaded at runtime rather than linked, so this
//! crate builds on a machine with no Pico software installed. A missing driver
//! surfaces when a unit is opened, not when the program is built.
//!
//! Bindings under `raw` are generated by bindgen and committed. Regenerating
//! them needs libclang and the PicoSDK headers; using them does not.

pub mod raw;

pub mod hrdl;

pub use hrdl::Hrdl;
