//! Raw driver bindings.
//!
//! Everything here is generated by bindgen and everything here is `unsafe`.
//! bindgen translates the header's syntax, not its meaning: it does not know
//! that a task handle must come from a create call, that a negative return is
//! a failure and a positive one only a warning, or that a pointer argument
//! needs storage you own. That knowledge lives in the safe wrappers one level
//! up, which is the only place these are called.

pub mod nidaqmx;
