/* automatically generated by rust-bindgen 0.72.1 */

//! Generated by bindgen from NIDAQmx.h. Do not edit by hand.
//! Regenerate with the command in nidaqmx/README.md.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
// Generated code cannot document its own safety, and a C function takes the
// arguments it takes. Neither is actionable here; both are answered one level
// up, in the safe wrappers.
#![allow(clippy::missing_safety_doc, clippy::too_many_arguments)]

pub const DAQmx_Val_GroupByChannel: u32 = 0;
pub const DAQmx_Val_GroupByScanNumber: u32 = 1;
pub const DAQmx_Val_Rising: u32 = 10280;
pub const DAQmx_Val_Falling: u32 = 10171;
pub const DAQmx_Val_Diff: u32 = 10106;
pub const DAQmx_Val_PseudoDiff: u32 = 12529;
pub const DAQmx_Val_Cfg_Default: i32 = -1;
pub const DAQmx_Val_WaitInfinitely: f64 = -1.0;
pub const DAQmx_Val_Auto: i32 = -1;
pub const DAQmx_Val_FiniteSamps: u32 = 10178;
pub const DAQmx_Val_ContSamps: u32 = 10123;
pub const DAQmx_Val_RSE: u32 = 10083;
pub const DAQmx_Val_NRSE: u32 = 10078;
pub const DAQmx_Val_Volts: u32 = 10348;
pub type int32 = ::std::os::raw::c_long;
pub type uInt32 = ::std::os::raw::c_ulong;
pub type float64 = f64;
pub type uInt64 = ::std::os::raw::c_ulonglong;
pub type bool32 = uInt32;
pub type TaskHandle = *mut ::std::os::raw::c_void;
pub struct NiDaqmx {
    __library: ::libloading::Library,
    pub DAQmxCreateTask: Result<
        unsafe extern "C" fn(
            taskName: *const ::std::os::raw::c_char,
            taskHandle: *mut TaskHandle,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxStartTask:
        Result<unsafe extern "C" fn(taskHandle: TaskHandle) -> int32, ::libloading::Error>,
    pub DAQmxStopTask:
        Result<unsafe extern "C" fn(taskHandle: TaskHandle) -> int32, ::libloading::Error>,
    pub DAQmxClearTask:
        Result<unsafe extern "C" fn(taskHandle: TaskHandle) -> int32, ::libloading::Error>,
    pub DAQmxWaitUntilTaskDone: Result<
        unsafe extern "C" fn(taskHandle: TaskHandle, timeToWait: float64) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxCreateAIVoltageChan: Result<
        unsafe extern "C" fn(
            taskHandle: TaskHandle,
            physicalChannel: *const ::std::os::raw::c_char,
            nameToAssignToChannel: *const ::std::os::raw::c_char,
            terminalConfig: int32,
            minVal: float64,
            maxVal: float64,
            units: int32,
            customScaleName: *const ::std::os::raw::c_char,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxCfgSampClkTiming: Result<
        unsafe extern "C" fn(
            taskHandle: TaskHandle,
            source: *const ::std::os::raw::c_char,
            rate: float64,
            activeEdge: int32,
            sampleMode: int32,
            sampsPerChan: uInt64,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxReadAnalogF64: Result<
        unsafe extern "C" fn(
            taskHandle: TaskHandle,
            numSampsPerChan: int32,
            timeout: float64,
            fillMode: bool32,
            readArray: *mut float64,
            arraySizeInSamps: uInt32,
            sampsPerChanRead: *mut int32,
            reserved: *mut bool32,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxReadAnalogScalarF64: Result<
        unsafe extern "C" fn(
            taskHandle: TaskHandle,
            timeout: float64,
            value: *mut float64,
            reserved: *mut bool32,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxResetDevice: Result<
        unsafe extern "C" fn(deviceName: *const ::std::os::raw::c_char) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxSelfTestDevice: Result<
        unsafe extern "C" fn(deviceName: *const ::std::os::raw::c_char) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetErrorString: Result<
        unsafe extern "C" fn(
            errorCode: int32,
            errorString: *mut ::std::os::raw::c_char,
            bufferSize: uInt32,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetExtendedErrorInfo: Result<
        unsafe extern "C" fn(errorString: *mut ::std::os::raw::c_char, bufferSize: uInt32) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetDevProductType: Result<
        unsafe extern "C" fn(
            device: *const ::std::os::raw::c_char,
            data: *mut ::std::os::raw::c_char,
            bufferSize: uInt32,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetDevSerialNum: Result<
        unsafe extern "C" fn(device: *const ::std::os::raw::c_char, data: *mut uInt32) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetDevAIPhysicalChans: Result<
        unsafe extern "C" fn(
            device: *const ::std::os::raw::c_char,
            data: *mut ::std::os::raw::c_char,
            bufferSize: uInt32,
        ) -> int32,
        ::libloading::Error,
    >,
    pub DAQmxGetSysDevNames: Result<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_char, bufferSize: uInt32) -> int32,
        ::libloading::Error,
    >,
}
impl NiDaqmx {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let DAQmxCreateTask = __library.get(b"DAQmxCreateTask\0").map(|sym| *sym);
        let DAQmxStartTask = __library.get(b"DAQmxStartTask\0").map(|sym| *sym);
        let DAQmxStopTask = __library.get(b"DAQmxStopTask\0").map(|sym| *sym);
        let DAQmxClearTask = __library.get(b"DAQmxClearTask\0").map(|sym| *sym);
        let DAQmxWaitUntilTaskDone = __library.get(b"DAQmxWaitUntilTaskDone\0").map(|sym| *sym);
        let DAQmxCreateAIVoltageChan = __library.get(b"DAQmxCreateAIVoltageChan\0").map(|sym| *sym);
        let DAQmxCfgSampClkTiming = __library.get(b"DAQmxCfgSampClkTiming\0").map(|sym| *sym);
        let DAQmxReadAnalogF64 = __library.get(b"DAQmxReadAnalogF64\0").map(|sym| *sym);
        let DAQmxReadAnalogScalarF64 = __library.get(b"DAQmxReadAnalogScalarF64\0").map(|sym| *sym);
        let DAQmxResetDevice = __library.get(b"DAQmxResetDevice\0").map(|sym| *sym);
        let DAQmxSelfTestDevice = __library.get(b"DAQmxSelfTestDevice\0").map(|sym| *sym);
        let DAQmxGetErrorString = __library.get(b"DAQmxGetErrorString\0").map(|sym| *sym);
        let DAQmxGetExtendedErrorInfo = __library
            .get(b"DAQmxGetExtendedErrorInfo\0")
            .map(|sym| *sym);
        let DAQmxGetDevProductType = __library.get(b"DAQmxGetDevProductType\0").map(|sym| *sym);
        let DAQmxGetDevSerialNum = __library.get(b"DAQmxGetDevSerialNum\0").map(|sym| *sym);
        let DAQmxGetDevAIPhysicalChans = __library
            .get(b"DAQmxGetDevAIPhysicalChans\0")
            .map(|sym| *sym);
        let DAQmxGetSysDevNames = __library.get(b"DAQmxGetSysDevNames\0").map(|sym| *sym);
        Ok(NiDaqmx {
            __library,
            DAQmxCreateTask,
            DAQmxStartTask,
            DAQmxStopTask,
            DAQmxClearTask,
            DAQmxWaitUntilTaskDone,
            DAQmxCreateAIVoltageChan,
            DAQmxCfgSampClkTiming,
            DAQmxReadAnalogF64,
            DAQmxReadAnalogScalarF64,
            DAQmxResetDevice,
            DAQmxSelfTestDevice,
            DAQmxGetErrorString,
            DAQmxGetExtendedErrorInfo,
            DAQmxGetDevProductType,
            DAQmxGetDevSerialNum,
            DAQmxGetDevAIPhysicalChans,
            DAQmxGetSysDevNames,
        })
    }
    pub unsafe fn DAQmxCreateTask(
        &self,
        taskName: *const ::std::os::raw::c_char,
        taskHandle: *mut TaskHandle,
    ) -> int32 {
        (self
            .DAQmxCreateTask
            .as_ref()
            .expect("Expected function, got error."))(taskName, taskHandle)
    }
    pub unsafe fn DAQmxStartTask(&self, taskHandle: TaskHandle) -> int32 {
        (self
            .DAQmxStartTask
            .as_ref()
            .expect("Expected function, got error."))(taskHandle)
    }
    pub unsafe fn DAQmxStopTask(&self, taskHandle: TaskHandle) -> int32 {
        (self
            .DAQmxStopTask
            .as_ref()
            .expect("Expected function, got error."))(taskHandle)
    }
    pub unsafe fn DAQmxClearTask(&self, taskHandle: TaskHandle) -> int32 {
        (self
            .DAQmxClearTask
            .as_ref()
            .expect("Expected function, got error."))(taskHandle)
    }
    pub unsafe fn DAQmxWaitUntilTaskDone(
        &self,
        taskHandle: TaskHandle,
        timeToWait: float64,
    ) -> int32 {
        (self
            .DAQmxWaitUntilTaskDone
            .as_ref()
            .expect("Expected function, got error."))(taskHandle, timeToWait)
    }
    #[doc = "/\n/***        Channel Configuration/Creation          ***/\n/"]
    pub unsafe fn DAQmxCreateAIVoltageChan(
        &self,
        taskHandle: TaskHandle,
        physicalChannel: *const ::std::os::raw::c_char,
        nameToAssignToChannel: *const ::std::os::raw::c_char,
        terminalConfig: int32,
        minVal: float64,
        maxVal: float64,
        units: int32,
        customScaleName: *const ::std::os::raw::c_char,
    ) -> int32 {
        (self
            .DAQmxCreateAIVoltageChan
            .as_ref()
            .expect("Expected function, got error."))(
            taskHandle,
            physicalChannel,
            nameToAssignToChannel,
            terminalConfig,
            minVal,
            maxVal,
            units,
            customScaleName,
        )
    }
    #[doc = "/\n/***                    Timing                      ***/\n/"]
    pub unsafe fn DAQmxCfgSampClkTiming(
        &self,
        taskHandle: TaskHandle,
        source: *const ::std::os::raw::c_char,
        rate: float64,
        activeEdge: int32,
        sampleMode: int32,
        sampsPerChan: uInt64,
    ) -> int32 {
        (self
            .DAQmxCfgSampClkTiming
            .as_ref()
            .expect("Expected function, got error."))(
            taskHandle,
            source,
            rate,
            activeEdge,
            sampleMode,
            sampsPerChan,
        )
    }
    #[doc = "/\n/***                 Read Data                      ***/\n/"]
    pub unsafe fn DAQmxReadAnalogF64(
        &self,
        taskHandle: TaskHandle,
        numSampsPerChan: int32,
        timeout: float64,
        fillMode: bool32,
        readArray: *mut float64,
        arraySizeInSamps: uInt32,
        sampsPerChanRead: *mut int32,
        reserved: *mut bool32,
    ) -> int32 {
        (self
            .DAQmxReadAnalogF64
            .as_ref()
            .expect("Expected function, got error."))(
            taskHandle,
            numSampsPerChan,
            timeout,
            fillMode,
            readArray,
            arraySizeInSamps,
            sampsPerChanRead,
            reserved,
        )
    }
    pub unsafe fn DAQmxReadAnalogScalarF64(
        &self,
        taskHandle: TaskHandle,
        timeout: float64,
        value: *mut float64,
        reserved: *mut bool32,
    ) -> int32 {
        (self
            .DAQmxReadAnalogScalarF64
            .as_ref()
            .expect("Expected function, got error."))(taskHandle, timeout, value, reserved)
    }
    #[doc = "/\n/***                Device Control                  ***/\n/"]
    pub unsafe fn DAQmxResetDevice(&self, deviceName: *const ::std::os::raw::c_char) -> int32 {
        (self
            .DAQmxResetDevice
            .as_ref()
            .expect("Expected function, got error."))(deviceName)
    }
    pub unsafe fn DAQmxSelfTestDevice(&self, deviceName: *const ::std::os::raw::c_char) -> int32 {
        (self
            .DAQmxSelfTestDevice
            .as_ref()
            .expect("Expected function, got error."))(deviceName)
    }
    #[doc = "/\n/***                 Error Handling                 ***/\n/"]
    pub unsafe fn DAQmxGetErrorString(
        &self,
        errorCode: int32,
        errorString: *mut ::std::os::raw::c_char,
        bufferSize: uInt32,
    ) -> int32 {
        (self
            .DAQmxGetErrorString
            .as_ref()
            .expect("Expected function, got error."))(errorCode, errorString, bufferSize)
    }
    pub unsafe fn DAQmxGetExtendedErrorInfo(
        &self,
        errorString: *mut ::std::os::raw::c_char,
        bufferSize: uInt32,
    ) -> int32 {
        (self
            .DAQmxGetExtendedErrorInfo
            .as_ref()
            .expect("Expected function, got error."))(errorString, bufferSize)
    }
    pub unsafe fn DAQmxGetDevProductType(
        &self,
        device: *const ::std::os::raw::c_char,
        data: *mut ::std::os::raw::c_char,
        bufferSize: uInt32,
    ) -> int32 {
        (self
            .DAQmxGetDevProductType
            .as_ref()
            .expect("Expected function, got error."))(device, data, bufferSize)
    }
    pub unsafe fn DAQmxGetDevSerialNum(
        &self,
        device: *const ::std::os::raw::c_char,
        data: *mut uInt32,
    ) -> int32 {
        (self
            .DAQmxGetDevSerialNum
            .as_ref()
            .expect("Expected function, got error."))(device, data)
    }
    pub unsafe fn DAQmxGetDevAIPhysicalChans(
        &self,
        device: *const ::std::os::raw::c_char,
        data: *mut ::std::os::raw::c_char,
        bufferSize: uInt32,
    ) -> int32 {
        (self
            .DAQmxGetDevAIPhysicalChans
            .as_ref()
            .expect("Expected function, got error."))(device, data, bufferSize)
    }
    pub unsafe fn DAQmxGetSysDevNames(
        &self,
        data: *mut ::std::os::raw::c_char,
        bufferSize: uInt32,
    ) -> int32 {
        (self
            .DAQmxGetSysDevNames
            .as_ref()
            .expect("Expected function, got error."))(data, bufferSize)
    }
}
